let DataPortfolioResumeMedia = [
    {
        id: 1,
        title: "نمونه کار شماره یک",
        date: "14 شهریور 1402",
        desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله",
        technologyOne: "HTML",
        technologyTwo: "CSS",
        technologyThree: "Bootstrap",
        technologyFour: "JavaScript",
        technologyFive: "React Js",
        img: "/img/1.jpg",
    },
    {
        id: 6,
        title: "نمونه کار شماره چهار",
        date: "12 فروردین 1400",
        desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله",
        technologyOne: "HTML",
        technologyTwo: "CSS",
        technologyThree: "Bootstrap",
        technologyFour: "JavaScript",
        technologyFive: "React Js",
        technologySix: "Redux Js",
        img: "/img/6.jpg",
    },
    {
        id: 8,
        title: "نمونه کار شماره سه",
        date: "28 تیر 1397",
        desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله",
        technologyOne: "HTML",
        technologyTwo: "CSS",
        technologyThree: "Bootstrap",
        technologyFour: "JavaScript",
        technologyFive: "React Js",
        technologySix: "Redux Js",
        img: "/img/8.jpg",
    },
    {
        id: 10,
        title: "نمونه کار شماره دو",
        date: "19 آبان 1396",
        desc: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله",
        technologyOne: "HTML",
        technologyTwo: "CSS",
        technologyThree: "Bootstrap",
        technologyFour: "JavaScript",
        technologyFive: "React Js",
        technologySix: "Redux Js",
        img: "/img/10.jpg",
    },
];

export default DataPortfolioResumeMedia;